version: "3"

services:
  moji:
    build:
      context: .
      dockerfile: support/Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "2950:2950"
    command: npm start

